### ISSUE TITLE
Help with filter

### ISSUE THREAD

**Issue by sofutru** [gwarser/filter-lists#1]
I'm sorry for intruding in your personal repo, but i want to ask how to combine this two filters: 
```
:has-text(/^[^:]+$/)
:not(:has(a[href="javascript:void(0)"]))
```
So that i can block comments that don't have `:` symbol in javacript link.

**Comment by gwarser** [comment]
No need for procedural filters to select links without `:`:

    ##a:not([href*=":"])

This is native (fast) CSS selector.

To hide _comments_, procedural will most likely be required, but I need more data.

**Comment by gwarser** [comment]
For "comments" like these:

```html
    <comment>
        <a href="javascript:void(0)">foo:bar</a>
    </comment>
    <comment>
        <a href="javascript:void(0)">foo-bar</a>
    </comment>
```

block comment with javascript link without `:` text:

    example.com##comment:has(a[href="javascript:void(0)"]:not(:has-text(:)))

**Comment by gwarser** [comment]
Blocking comments without time mark in YT can be very sloow on videos with lot of comments - they will be loaded all the time until enough comments with timestamp will be found.

**Comment by sofutru** [comment]
The last filter is perfect, thanks!

**Comment by sofutru** [comment]
@gwarser last filter passes through comment witch ":" in nickname, so it's not perfect after all, so i want to use this: `invidiou.us###comments:has(a[href="javascript:void(0)"]:not(:has-text(:))) > div > div.pure-g` filter, can you fix it please?

**Comment by gwarser** [comment]
`invidioU.us`?

**Comment by sofutru** [comment]
@gwarser It's mistype and mishap after ctrl+v mistake, yeah, now this IS perfect, thank you again.

**Comment by bogachenko** [comment]
@gwarser _I do not want to open a new issue, since the topic of this discussion fits my own._

Explain your regexp (for dumb ones) https://github.com/gwarser/filter-lists/blob/master/lan-block.txt#L19
`/^https?://10\.(?:(?:[0-9]|[1-9][0-9]|1(?:[0-9][0-9])|2(?:[0-4][0-9]|5[0-5]))\.){2}(?:[0-9]|[1-9][0-9]|1(?:[0-9][0-9])|2(?:[0-4][0-9]|5[0-5]))[:/]/$third-party`
Namely, how and why you wrote it `?:` with this `[0-9]`.  It doesn’t work for me.

Look man, for eg. I want to block the domain `https://example.com/` using regexp, I wrote one
`/exa(?:[mp]|l)e\.com/$important` But it does not block, where is my problem?

WHY?
